# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

REMI_run <- function(stringname1, stringname2, method, nstep, gamseq, eps = 0.05, bandwidth = 200L, shrinkagefactor = 0.9) {
    .Call('_REMI_REMI_run', PACKAGE = 'REMI', stringname1, stringname2, method, nstep, gamseq, eps, bandwidth, shrinkagefactor)
}

REMI_run_Jiao <- function(stringname1, stringname2, nstep, eps = 0.05, bandwidth = 200L, shrinkagefactor = 0.9) {
    .Call('_REMI_REMI_run_Jiao', PACKAGE = 'REMI', stringname1, stringname2, nstep, eps, bandwidth, shrinkagefactor)
}

pred_REMI <- function(stringname, rsname, A1_r, A2_r, whCol, betah) {
    .Call('_REMI_pred_REMI', PACKAGE = 'REMI', stringname, rsname, A1_r, A2_r, whCol, betah)
}

rcpp_bicSsLasso <- function(betah, s2, R, nstep, eps, n) {
    .Call('_REMI_rcpp_bicSsLasso', PACKAGE = 'REMI', betah, s2, R, nstep, eps, n)
}

ReadPlinkFile <- function(stringname) {
    .Call('_REMI_ReadPlinkFile', PACKAGE = 'REMI', stringname)
}

lasso_geno <- function(stringname, method, nstep, gamseq, eps) {
    .Call('_REMI_lasso_geno', PACKAGE = 'REMI', stringname, method, nstep, gamseq, eps)
}

lasso <- function(X, Y, X_var, nstep, eps) {
    .Call('_REMI_lasso', PACKAGE = 'REMI', X, Y, X_var, nstep, eps)
}

bicSsLasso_Jiao <- function(ytilde, Sigma, nstep, eps, n, sigma2) {
    .Call('_REMI_bicSsLasso_Jiao', PACKAGE = 'REMI', ytilde, Sigma, nstep, eps, n, sigma2)
}

